--
-- RISE — the whole database, in one file.
--
-- This is what create-database.sh applies. See freeze-schema.sh for how it is
-- built and why it exists rather than the migrations that produced it.
--
-- ==== everything below is generated by freeze-schema.sh — do not edit ====

--
--

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;

--
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: _migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public._migrations (
    name text NOT NULL,
    run_at timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: answer_criterion_scores; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.answer_criterion_scores (
    answer_feedback_id uuid NOT NULL,
    competency text NOT NULL,
    score numeric(3,2) NOT NULL,
    CONSTRAINT answer_criterion_scores_score_check CHECK (((score >= (0)::numeric) AND (score <= (5)::numeric)))
);

--
-- Name: answer_feedback; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.answer_feedback (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    session_id uuid NOT NULL,
    question_id text NOT NULL,
    answer_message_id uuid,
    student_answer text NOT NULL,
    ai_feedback_json jsonb NOT NULL,
    overall_score numeric(3,2),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    answer_char_count integer,
    dictated boolean DEFAULT false NOT NULL,
    CONSTRAINT answer_feedback_answer_char_count_check CHECK (((answer_char_count IS NULL) OR (answer_char_count >= 0)))
);

--
-- Name: COLUMN answer_feedback.answer_char_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.answer_feedback.answer_char_count IS 'Character length of student_answer, recorded separately so it survives encryption of the answer itself.';

--
-- Name: COLUMN answer_feedback.dictated; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.answer_feedback.dictated IS 'Answer was dictated and transcribed rather than typed. The student reviewed and could edit the transcript before submitting, so the stored text is theirs, not the transcriber''s.';

--
-- Name: audit_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_log (
    id bigint NOT NULL,
    occurred_at timestamp with time zone DEFAULT now() NOT NULL,
    actor_id uuid,
    actor_role text NOT NULL,
    action text NOT NULL,
    subject_id uuid,
    object_id uuid,
    result_count integer,
    actor_label text,
    subject_label text,
    CONSTRAINT audit_log_action_check CHECK ((action = ANY (ARRAY['read_transcript'::text, 'read_profile'::text, 'list_students'::text, 'export'::text, 'erase'::text, 'suspend'::text, 'reactivate'::text])))
);

--
-- Name: TABLE audit_log; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.audit_log IS 'Access records for student personal data. Contains no content. Retain 12 months — see DPIA.md §3.6 and §4.2.';

--
-- Name: COLUMN audit_log.subject_label; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.audit_log.subject_label IS 'Who the subject was when the action happened. Survives their deletion, which is the point.';

--
-- Name: audit_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: audit_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.audit_log_id_seq OWNED BY public.audit_log.id;

--
-- Name: content_questions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_questions (
    version_id uuid NOT NULL,
    question_id text NOT NULL,
    scenario_id text NOT NULL,
    "order" integer NOT NULL,
    question_sr text DEFAULT ''::text NOT NULL,
    question_en text DEFAULT ''::text NOT NULL,
    question_fr text DEFAULT ''::text NOT NULL,
    question_pt text DEFAULT ''::text NOT NULL,
    type text DEFAULT ''::text NOT NULL,
    competency text DEFAULT ''::text NOT NULL,
    expected_answer text DEFAULT ''::text NOT NULL,
    eqf_level text DEFAULT ''::text NOT NULL,
    type_source text DEFAULT ''::text NOT NULL
);

--
-- Name: content_rubrics; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_rubrics (
    version_id uuid NOT NULL,
    rubric_id text NOT NULL,
    scenario_id text NOT NULL,
    competency text DEFAULT ''::text NOT NULL,
    label_sr text DEFAULT ''::text NOT NULL,
    label_en text DEFAULT ''::text NOT NULL,
    label_fr text DEFAULT ''::text NOT NULL,
    label_pt text DEFAULT ''::text NOT NULL,
    description_sr text DEFAULT ''::text NOT NULL,
    description_en text DEFAULT ''::text NOT NULL,
    description_fr text DEFAULT ''::text NOT NULL,
    description_pt text DEFAULT ''::text NOT NULL,
    weight numeric(4,3) DEFAULT 0 NOT NULL
);

--
-- Name: content_scenarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_scenarios (
    version_id uuid NOT NULL,
    scenario_id text NOT NULL,
    profession text DEFAULT ''::text NOT NULL,
    title_sr text DEFAULT ''::text NOT NULL,
    title_en text DEFAULT ''::text NOT NULL,
    title_fr text DEFAULT ''::text NOT NULL,
    title_pt text DEFAULT ''::text NOT NULL,
    description_sr text DEFAULT ''::text NOT NULL,
    description_en text DEFAULT ''::text NOT NULL,
    description_fr text DEFAULT ''::text NOT NULL,
    description_pt text DEFAULT ''::text NOT NULL,
    language text DEFAULT ''::text NOT NULL,
    difficulty text DEFAULT ''::text NOT NULL,
    sector text DEFAULT ''::text NOT NULL,
    eqf_level text DEFAULT ''::text NOT NULL,
    question_count integer,
    active boolean DEFAULT true NOT NULL
);

--
-- Name: content_versions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_versions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    source_sheet_id text,
    imported_at timestamp with time zone DEFAULT now() NOT NULL,
    imported_by uuid,
    is_current boolean DEFAULT false NOT NULL,
    scenario_count integer DEFAULT 0 NOT NULL,
    question_count integer DEFAULT 0 NOT NULL,
    rubric_count integer DEFAULT 0 NOT NULL,
    note text
);

--
-- Name: data_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.data_requests (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    kind text NOT NULL,
    requested_at timestamp with time zone DEFAULT now() NOT NULL,
    due_at timestamp with time zone NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    handled_by uuid,
    handled_at timestamp with time zone,
    note text,
    CONSTRAINT data_requests_kind_check CHECK ((kind = ANY (ARRAY['export'::text, 'erasure'::text]))),
    CONSTRAINT data_requests_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'completed'::text, 'refused'::text, 'cancelled'::text])))
);

--
-- Name: group_students; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.group_students (
    group_id uuid NOT NULL,
    user_id uuid NOT NULL
);

--
-- Name: group_teachers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.group_teachers (
    group_id uuid NOT NULL,
    user_id uuid NOT NULL
);

--
-- Name: groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.groups (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    name text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: interview_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.interview_messages (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    session_id uuid NOT NULL,
    sender text NOT NULL,
    message_type text NOT NULL,
    question_id text,
    content text NOT NULL,
    llm_model text,
    prompt_tokens integer,
    completion_tokens integer,
    total_tokens integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    cost_eur numeric(14,10),
    co2e_g numeric(14,8),
    water_l numeric(14,8),
    pricing_version text,
    CONSTRAINT interview_messages_completion_tokens_check CHECK (((completion_tokens IS NULL) OR (completion_tokens >= 0))),
    CONSTRAINT interview_messages_llm_usage_message_type_check CHECK ((((llm_model IS NULL) AND (prompt_tokens IS NULL) AND (completion_tokens IS NULL) AND (total_tokens IS NULL)) OR (message_type = ANY (ARRAY['feedback'::text, 'summary'::text])))),
    CONSTRAINT interview_messages_message_type_check CHECK ((message_type = ANY (ARRAY['question'::text, 'answer'::text, 'feedback'::text, 'summary'::text]))),
    CONSTRAINT interview_messages_prompt_tokens_check CHECK (((prompt_tokens IS NULL) OR (prompt_tokens >= 0))),
    CONSTRAINT interview_messages_sender_check CHECK ((sender = ANY (ARRAY['student'::text, 'ai'::text, 'system'::text]))),
    CONSTRAINT interview_messages_total_tokens_check CHECK (((total_tokens IS NULL) OR (total_tokens >= 0)))
);

--
-- Name: COLUMN interview_messages.cost_eur; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.interview_messages.cost_eur IS 'Estimated cost in EUR from Scaleway retail list prices. Not a billed amount.';

--
-- Name: COLUMN interview_messages.co2e_g; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.interview_messages.co2e_g IS 'Estimated CO2 equivalent in grams, from Scaleway published per-token figures.';

--
-- Name: COLUMN interview_messages.water_l; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.interview_messages.water_l IS 'Estimated water usage in litres, from Scaleway published per-token figures.';

--
-- Name: COLUMN interview_messages.pricing_version; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.interview_messages.pricing_version IS 'Rate table applied, matching backend/pricing/scaleway.json version.';

--
-- Name: interview_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.interview_sessions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    student_id uuid NOT NULL,
    scenario_id text NOT NULL,
    language text NOT NULL,
    status text NOT NULL,
    attempt_number integer DEFAULT 1 NOT NULL,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    completed_at timestamp with time zone,
    content_version_id uuid,
    CONSTRAINT interview_sessions_language_check CHECK ((language = ANY (ARRAY['sr'::text, 'en'::text, 'fr'::text, 'pt'::text]))),
    CONSTRAINT interview_sessions_status_check CHECK ((status = ANY (ARRAY['in_progress'::text, 'completed'::text, 'abandoned'::text])))
);

--
-- Name: org_content_source; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.org_content_source (
    org_id uuid NOT NULL,
    spreadsheet_id text,
    updated_by uuid,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    last_checked_at timestamp with time zone,
    last_check_ok boolean,
    last_check_message text
);

--
-- Name: COLUMN org_content_source.spreadsheet_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.org_content_source.spreadsheet_id IS 'Google Sheets file id. NULL means the organization has no content of its own yet and serves nothing.';

--
-- Name: COLUMN org_content_source.last_check_ok; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.org_content_source.last_check_ok IS 'Result of the last connection test, so an administrator who pastes a bad id finds out at that moment rather than when a class sits down.';

--
-- Name: org_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.org_settings (
    org_id uuid NOT NULL,
    short_name text,
    legal_name text,
    dpo_name text,
    dpo_email text,
    dpo_phone text,
    lawful_basis_students text,
    lawful_basis_staff text,
    retention_answers_value integer,
    retention_answers_unit text,
    retention_account_value integer,
    retention_account_unit text,
    retention_staff_value integer,
    retention_staff_unit text,
    supervisory_authority text,
    support_name text,
    support_email text,
    support_phone text,
    support_hours text,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_by uuid,
    CONSTRAINT org_settings_lawful_basis_staff_check CHECK (((lawful_basis_staff IS NULL) OR (lawful_basis_staff = ANY (ARRAY['public_task'::text, 'contract'::text])))),
    CONSTRAINT org_settings_lawful_basis_students_check CHECK (((lawful_basis_students IS NULL) OR (lawful_basis_students = ANY (ARRAY['public_task'::text, 'legal_obligation'::text, 'consent'::text])))),
    CONSTRAINT org_settings_retention_account_unit_check CHECK (((retention_account_unit IS NULL) OR (retention_account_unit = ANY (ARRAY['days'::text, 'months'::text, 'years'::text])))),
    CONSTRAINT org_settings_retention_account_value_check CHECK (((retention_account_value IS NULL) OR (retention_account_value > 0))),
    CONSTRAINT org_settings_retention_answers_unit_check CHECK (((retention_answers_unit IS NULL) OR (retention_answers_unit = ANY (ARRAY['days'::text, 'months'::text, 'years'::text])))),
    CONSTRAINT org_settings_retention_answers_value_check CHECK (((retention_answers_value IS NULL) OR (retention_answers_value > 0))),
    CONSTRAINT org_settings_retention_staff_unit_check CHECK (((retention_staff_unit IS NULL) OR (retention_staff_unit = ANY (ARRAY['days'::text, 'months'::text, 'years'::text])))),
    CONSTRAINT org_settings_retention_staff_value_check CHECK (((retention_staff_value IS NULL) OR (retention_staff_value > 0)))
);

--
-- Name: organizations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.organizations (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    slug text NOT NULL,
    name text NOT NULL,
    country text,
    default_language text,
    status text DEFAULT 'active'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    attempts_per_scenario integer,
    total_interviews integer,
    cooldown_days integer,
    CONSTRAINT organizations_attempts_per_scenario_check CHECK (((attempts_per_scenario IS NULL) OR (attempts_per_scenario >= 0))),
    CONSTRAINT organizations_cooldown_days_check CHECK (((cooldown_days IS NULL) OR (cooldown_days >= 0))),
    CONSTRAINT organizations_default_language_check CHECK ((default_language = ANY (ARRAY['sr'::text, 'en'::text, 'fr'::text, 'pt'::text]))),
    CONSTRAINT organizations_status_check CHECK ((status = ANY (ARRAY['active'::text, 'suspended'::text, 'closed'::text]))),
    CONSTRAINT organizations_total_interviews_check CHECK (((total_interviews IS NULL) OR (total_interviews >= 0)))
);

--
-- Name: password_resets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.password_resets (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    token_hash text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: TABLE password_resets; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.password_resets IS 'One row per reset request. Single use, short lived, hashed. Rows are expired by the retention job alongside everything else; nothing here outlives its usefulness by more than a day.';

--
-- Name: platform_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.platform_settings (
    id boolean DEFAULT true NOT NULL,
    attempts_per_scenario integer DEFAULT 3 NOT NULL,
    total_interviews integer DEFAULT 15 NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_by uuid,
    cooldown_days integer DEFAULT 7 NOT NULL,
    support_name text,
    support_email text,
    CONSTRAINT platform_settings_attempts_per_scenario_check CHECK ((attempts_per_scenario >= 0)),
    CONSTRAINT platform_settings_cooldown_days_check CHECK ((cooldown_days >= 0)),
    CONSTRAINT platform_settings_id_check CHECK (id),
    CONSTRAINT platform_settings_total_interviews_check CHECK ((total_interviews >= 0))
);

--
-- Name: session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.session (
    sid character varying NOT NULL,
    sess json NOT NULL,
    expire timestamp(6) without time zone NOT NULL
);

--
-- Name: transcription_calls; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transcription_calls (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    session_id uuid,
    org_id uuid,
    model text NOT NULL,
    audio_seconds numeric(8,2) NOT NULL,
    cost_eur numeric(12,8),
    co2e_g numeric(12,6),
    water_l numeric(12,9),
    pricing_version text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT transcription_calls_audio_seconds_check CHECK ((audio_seconds >= (0)::numeric))
);

--
-- Name: TABLE transcription_calls; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.transcription_calls IS 'One row per speech-to-text call, including calls whose audio never became a submitted answer. Survives erasure of the student with its foreign keys nulled.';

--
-- Name: COLUMN transcription_calls.co2e_g; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.transcription_calls.co2e_g IS 'NULL means Scaleway publishes no figure for this model. As of the 2026-09-03 catalog, whisper-large-v3 reports kg_co2_equivalent = 0 and omits water usage entirely, which is an absence of measurement rather than an absence of impact — do not sum these as though the zeros were measured.';

--
-- Name: user_invitations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_invitations (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    email text,
    display_name text,
    role text NOT NULL,
    preferred_language text,
    token_hash text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    accepted_at timestamp with time zone,
    invited_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    org_id uuid,
    CONSTRAINT user_invitations_preferred_language_check CHECK ((preferred_language = ANY (ARRAY['sr'::text, 'en'::text, 'fr'::text, 'pt'::text]))),
    CONSTRAINT user_invitations_role_check CHECK ((role = ANY (ARRAY['student'::text, 'teacher'::text, 'admin'::text])))
);

--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    email text NOT NULL,
    password_hash text NOT NULL,
    display_name text NOT NULL,
    role text NOT NULL,
    preferred_language text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    question_count integer,
    notice_version text,
    notice_language text,
    notice_ack_at timestamp with time zone,
    org_id uuid,
    status text DEFAULT 'active'::text NOT NULL,
    CONSTRAINT users_notice_language_check CHECK ((notice_language = ANY (ARRAY['sr'::text, 'en'::text, 'fr'::text, 'pt'::text]))),
    CONSTRAINT users_org_scope_chk CHECK ((((role = 'super_admin'::text) AND (org_id IS NULL)) OR ((role <> 'super_admin'::text) AND (org_id IS NOT NULL)))),
    CONSTRAINT users_preferred_language_check CHECK ((preferred_language = ANY (ARRAY['sr'::text, 'en'::text, 'fr'::text, 'pt'::text]))),
    CONSTRAINT users_question_count_check CHECK (((question_count IS NULL) OR ((question_count >= 1) AND (question_count <= 50)))),
    CONSTRAINT users_role_check CHECK ((role = ANY (ARRAY['student'::text, 'teacher'::text, 'admin'::text, 'super_admin'::text]))),
    CONSTRAINT users_status_check CHECK ((status = ANY (ARRAY['active'::text, 'suspended'::text])))
);

--
-- Name: COLUMN users.status; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.users.status IS 'active | suspended. Suspension blocks sign-in and every authenticated request, and is reversible. It deletes nothing: see the erasure route for that.';

--
-- Name: audit_log id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_log ALTER COLUMN id SET DEFAULT nextval('public.audit_log_id_seq'::regclass);

--
-- Name: _migrations _migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public._migrations
    ADD CONSTRAINT _migrations_pkey PRIMARY KEY (name);

--
-- Name: answer_criterion_scores answer_criterion_scores_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.answer_criterion_scores
    ADD CONSTRAINT answer_criterion_scores_pkey PRIMARY KEY (answer_feedback_id, competency);

--
-- Name: answer_feedback answer_feedback_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.answer_feedback
    ADD CONSTRAINT answer_feedback_pkey PRIMARY KEY (id);

--
-- Name: answer_feedback answer_feedback_session_question_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.answer_feedback
    ADD CONSTRAINT answer_feedback_session_question_key UNIQUE (session_id, question_id);

--
-- Name: audit_log audit_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);

--
-- Name: content_questions content_questions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_questions
    ADD CONSTRAINT content_questions_pkey PRIMARY KEY (version_id, question_id);

--
-- Name: content_rubrics content_rubrics_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_rubrics
    ADD CONSTRAINT content_rubrics_pkey PRIMARY KEY (version_id, rubric_id);

--
-- Name: content_scenarios content_scenarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_scenarios
    ADD CONSTRAINT content_scenarios_pkey PRIMARY KEY (version_id, scenario_id);

--
-- Name: content_versions content_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_versions
    ADD CONSTRAINT content_versions_pkey PRIMARY KEY (id);

--
-- Name: data_requests data_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.data_requests
    ADD CONSTRAINT data_requests_pkey PRIMARY KEY (id);

--
-- Name: group_students group_students_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_students
    ADD CONSTRAINT group_students_pkey PRIMARY KEY (group_id, user_id);

--
-- Name: group_teachers group_teachers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_teachers
    ADD CONSTRAINT group_teachers_pkey PRIMARY KEY (group_id, user_id);

--
-- Name: groups groups_org_id_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.groups
    ADD CONSTRAINT groups_org_id_name_key UNIQUE (org_id, name);

--
-- Name: groups groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.groups
    ADD CONSTRAINT groups_pkey PRIMARY KEY (id);

--
-- Name: interview_messages interview_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_messages
    ADD CONSTRAINT interview_messages_pkey PRIMARY KEY (id);

--
-- Name: interview_sessions interview_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_sessions
    ADD CONSTRAINT interview_sessions_pkey PRIMARY KEY (id);

--
-- Name: org_content_source org_content_source_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.org_content_source
    ADD CONSTRAINT org_content_source_pkey PRIMARY KEY (org_id);

--
-- Name: org_settings org_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.org_settings
    ADD CONSTRAINT org_settings_pkey PRIMARY KEY (org_id);

--
-- Name: organizations organizations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organizations
    ADD CONSTRAINT organizations_pkey PRIMARY KEY (id);

--
-- Name: organizations organizations_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organizations
    ADD CONSTRAINT organizations_slug_key UNIQUE (slug);

--
-- Name: password_resets password_resets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_resets
    ADD CONSTRAINT password_resets_pkey PRIMARY KEY (id);

--
-- Name: password_resets password_resets_token_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_resets
    ADD CONSTRAINT password_resets_token_hash_key UNIQUE (token_hash);

--
-- Name: platform_settings platform_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.platform_settings
    ADD CONSTRAINT platform_settings_pkey PRIMARY KEY (id);

--
-- Name: session session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session
    ADD CONSTRAINT session_pkey PRIMARY KEY (sid);

--
-- Name: transcription_calls transcription_calls_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transcription_calls
    ADD CONSTRAINT transcription_calls_pkey PRIMARY KEY (id);

--
-- Name: user_invitations user_invitations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_invitations
    ADD CONSTRAINT user_invitations_pkey PRIMARY KEY (id);

--
-- Name: user_invitations user_invitations_token_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_invitations
    ADD CONSTRAINT user_invitations_token_hash_key UNIQUE (token_hash);

--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);

--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

--
-- Name: IDX_session_expire; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IDX_session_expire" ON public.session USING btree (expire);

--
-- Name: answer_criterion_scores_competency_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX answer_criterion_scores_competency_idx ON public.answer_criterion_scores USING btree (competency);

--
-- Name: answer_feedback_session_created_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX answer_feedback_session_created_idx ON public.answer_feedback USING btree (session_id, created_at);

--
-- Name: audit_log_actor_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_log_actor_idx ON public.audit_log USING btree (actor_id, occurred_at DESC);

--
-- Name: audit_log_subject_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_log_subject_idx ON public.audit_log USING btree (subject_id, occurred_at DESC);

--
-- Name: content_questions_scenario_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX content_questions_scenario_idx ON public.content_questions USING btree (version_id, scenario_id);

--
-- Name: content_rubrics_scenario_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX content_rubrics_scenario_idx ON public.content_rubrics USING btree (version_id, scenario_id);

--
-- Name: content_versions_one_current; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX content_versions_one_current ON public.content_versions USING btree (org_id) WHERE is_current;

--
-- Name: content_versions_org_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX content_versions_org_idx ON public.content_versions USING btree (org_id, imported_at DESC);

--
-- Name: data_requests_one_open_per_kind; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX data_requests_one_open_per_kind ON public.data_requests USING btree (user_id, kind) WHERE (status = 'pending'::text);

--
-- Name: data_requests_pending_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX data_requests_pending_idx ON public.data_requests USING btree (due_at) WHERE (status = 'pending'::text);

--
-- Name: data_requests_user_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX data_requests_user_idx ON public.data_requests USING btree (user_id, requested_at DESC);

--
-- Name: group_students_user_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX group_students_user_idx ON public.group_students USING btree (user_id);

--
-- Name: group_teachers_user_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX group_teachers_user_idx ON public.group_teachers USING btree (user_id);

--
-- Name: interview_messages_session_created_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX interview_messages_session_created_idx ON public.interview_messages USING btree (session_id, created_at);

--
-- Name: interview_sessions_content_version_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX interview_sessions_content_version_idx ON public.interview_sessions USING btree (content_version_id);

--
-- Name: interview_sessions_student_scenario_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX interview_sessions_student_scenario_idx ON public.interview_sessions USING btree (student_id, scenario_id);

--
-- Name: interview_sessions_student_started_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX interview_sessions_student_started_idx ON public.interview_sessions USING btree (student_id, started_at DESC);

--
-- Name: password_resets_user_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX password_resets_user_idx ON public.password_resets USING btree (user_id, created_at DESC);

--
-- Name: transcription_calls_created_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX transcription_calls_created_idx ON public.transcription_calls USING btree (created_at);

--
-- Name: transcription_calls_org_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX transcription_calls_org_idx ON public.transcription_calls USING btree (org_id, created_at);

--
-- Name: user_invitations_email_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_invitations_email_idx ON public.user_invitations USING btree (lower(email));

--
-- Name: user_invitations_org_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_invitations_org_idx ON public.user_invitations USING btree (org_id);

--
-- Name: user_invitations_pending_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_invitations_pending_idx ON public.user_invitations USING btree (expires_at) WHERE (accepted_at IS NULL);

--
-- Name: users_org_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_org_idx ON public.users USING btree (org_id, role);

--
-- Name: users_status_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_status_idx ON public.users USING btree (status) WHERE (status <> 'active'::text);

--
-- Name: answer_criterion_scores answer_criterion_scores_answer_feedback_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.answer_criterion_scores
    ADD CONSTRAINT answer_criterion_scores_answer_feedback_id_fkey FOREIGN KEY (answer_feedback_id) REFERENCES public.answer_feedback(id) ON DELETE CASCADE;

--
-- Name: answer_feedback answer_feedback_answer_message_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.answer_feedback
    ADD CONSTRAINT answer_feedback_answer_message_id_fkey FOREIGN KEY (answer_message_id) REFERENCES public.interview_messages(id) ON DELETE SET NULL;

--
-- Name: answer_feedback answer_feedback_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.answer_feedback
    ADD CONSTRAINT answer_feedback_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.interview_sessions(id) ON DELETE CASCADE;

--
-- Name: content_questions content_questions_version_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_questions
    ADD CONSTRAINT content_questions_version_id_fkey FOREIGN KEY (version_id) REFERENCES public.content_versions(id) ON DELETE CASCADE;

--
-- Name: content_rubrics content_rubrics_version_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_rubrics
    ADD CONSTRAINT content_rubrics_version_id_fkey FOREIGN KEY (version_id) REFERENCES public.content_versions(id) ON DELETE CASCADE;

--
-- Name: content_scenarios content_scenarios_version_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_scenarios
    ADD CONSTRAINT content_scenarios_version_id_fkey FOREIGN KEY (version_id) REFERENCES public.content_versions(id) ON DELETE CASCADE;

--
-- Name: content_versions content_versions_imported_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_versions
    ADD CONSTRAINT content_versions_imported_by_fkey FOREIGN KEY (imported_by) REFERENCES public.users(id) ON DELETE SET NULL;

--
-- Name: content_versions content_versions_org_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_versions
    ADD CONSTRAINT content_versions_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id) ON DELETE CASCADE;

--
-- Name: data_requests data_requests_handled_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.data_requests
    ADD CONSTRAINT data_requests_handled_by_fkey FOREIGN KEY (handled_by) REFERENCES public.users(id) ON DELETE SET NULL;

--
-- Name: data_requests data_requests_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.data_requests
    ADD CONSTRAINT data_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

--
-- Name: group_students group_students_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_students
    ADD CONSTRAINT group_students_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.groups(id) ON DELETE CASCADE;

--
-- Name: group_students group_students_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_students
    ADD CONSTRAINT group_students_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

--
-- Name: group_teachers group_teachers_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_teachers
    ADD CONSTRAINT group_teachers_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.groups(id) ON DELETE CASCADE;

--
-- Name: group_teachers group_teachers_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_teachers
    ADD CONSTRAINT group_teachers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

--
-- Name: groups groups_org_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.groups
    ADD CONSTRAINT groups_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id) ON DELETE CASCADE;

--
-- Name: interview_messages interview_messages_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_messages
    ADD CONSTRAINT interview_messages_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.interview_sessions(id) ON DELETE CASCADE;

--
-- Name: interview_sessions interview_sessions_content_version_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_sessions
    ADD CONSTRAINT interview_sessions_content_version_id_fkey FOREIGN KEY (content_version_id) REFERENCES public.content_versions(id) ON DELETE RESTRICT;

--
-- Name: interview_sessions interview_sessions_student_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_sessions
    ADD CONSTRAINT interview_sessions_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.users(id) ON DELETE CASCADE;

--
-- Name: org_content_source org_content_source_org_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.org_content_source
    ADD CONSTRAINT org_content_source_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id) ON DELETE CASCADE;

--
-- Name: org_content_source org_content_source_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.org_content_source
    ADD CONSTRAINT org_content_source_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id) ON DELETE SET NULL;

--
-- Name: org_settings org_settings_org_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.org_settings
    ADD CONSTRAINT org_settings_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id) ON DELETE CASCADE;

--
-- Name: password_resets password_resets_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_resets
    ADD CONSTRAINT password_resets_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

--
-- Name: transcription_calls transcription_calls_org_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transcription_calls
    ADD CONSTRAINT transcription_calls_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id) ON DELETE SET NULL;

--
-- Name: transcription_calls transcription_calls_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transcription_calls
    ADD CONSTRAINT transcription_calls_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.interview_sessions(id) ON DELETE SET NULL;

--
-- Name: user_invitations user_invitations_invited_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_invitations
    ADD CONSTRAINT user_invitations_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES public.users(id) ON DELETE SET NULL;

--
-- Name: user_invitations user_invitations_org_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_invitations
    ADD CONSTRAINT user_invitations_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id) ON DELETE CASCADE;

--
-- Name: users users_org_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id) ON DELETE CASCADE;

--
--

--
-- The platform defaults row. Structure, not data: see freeze-schema.sh.
--
INSERT INTO public.platform_settings (id) VALUES (true) ON CONFLICT (id) DO NOTHING;
